### ISSUE TITLE
List of Locations

### ISSUE THREAD

**Issue by pascalweber85** [pascalweber85/capstone-project#1]
### User Story I

As a user I want to have a overview about all Locations as Cards to see everything.
Description (text, scribble, wireframe, design)

<img width="238" alt="Bildschirmfoto 2021-06-03 um 16 01 27" src="https://user-images.githubusercontent.com/82396056/120660917-1c0ad380-c488-11eb-9d02-632646ae4a58.png">

### Text:

H1: Locations (title)
H2: Zoo
Kategorie: Freizeit

### Acceptance Criteria for Cards:

- [x] "Locations" as Title with H1
Different Cards which contains a list of:
- [x] an image: 100*100px 
- [x] a title as h2
- [x] a rating as symbols
- [x] Categorie as text 
 
### Task:

- [x]  feature branch
- [x]  Create 20 Cards as an Array
- [x]  add components and write a test

### Complexity:

low

**Comment by pascalweber85** [comment]
As a user I want to see all sightseeing Locations.

Description (text, scribble, wireframe, design)
<img width="156" alt="Bildschirmfoto 2021-06-03 um 10 37 42" src="https://user-images.githubusercontent.com/82396056/120614642-bdc5fc80-c457-11eb-86fc-0695a41f41ba.png">
