### ISSUE TITLE
Details for every Location

### ISSUE THREAD

**Issue by pascalweber85** [pascalweber85/capstone-project#2]
### User Story II

As User i want to click on every Location to see more details about it.

### Description (Text, Scribble, Wireframe, Design)

<img width="452" alt="Bildschirmfoto 2021-06-03 um 16 49 03" src="https://user-images.githubusercontent.com/82396056/120664970-a7d22f00-c48b-11eb-9864-87bf1890b3b2.png">

### Text
- H2: Name of Location
- H3: Öffnungszeiten
- H3: Beschreibung
- text: description

### Acceptance criteria

- [x] With click on a Picture  from "Location" you get linked to "Details"
- [x] The button 'back' brings me back to the "Locations"
- [x] header as h2 
- [x] Image 200*100px with symbols in it
- [x] h3: Öffnungszeiten
- [x] Details as unorderd List  
- [x] text: geöffnet/geschlossen
- [x] h3: Beschreibung
- [x] text: description

### Tasks

- [x] feature branch
- [x] Component w/ storybook and test
- [x] Update App with component and logic

### Complexity

low
