### ISSUE TITLE
Create Save as Favorite Button

### ISSUE THREAD

**Issue by pascalweber85** [pascalweber85/capstone-project#3]
### User Story III

as User i want to click the "save as favorite" Button to get to the Favorite Site and see my Favorites

### Description (Text, Scribble, Wireframe, Design)

<img width="653" alt="Bildschirmfoto 2021-06-03 um 17 11 31" src="https://user-images.githubusercontent.com/82396056/120668491-ce459980-c48e-11eb-9360-9f6414c93494.png">

### Text
Button: save as favorite
Button: Favorite
text H2 : Favorites

### Acceptance criteria
- [x] The "save as Favorite" button is implemented to the "Details-Site" and bring the user to the "Favorite" site and shows the Location there
- [x] all Favorite-Locations have a bookmark, which is toggleable
- [x] implement a go back Button at the Favorite-site, which brings you back to "Locations"
- [x] add a favorite Button to the location - when click leads you to Favorite Site

### Tasks
- [x] feature branch
- [ ] Component w/ storybook and test
- [x] Update App with component and logic

### Complexity

medium
